name: Build latest tag

# on: 
#   push:
#     tags: ["v*"]
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: configue gitbook
        run: |
          npm install -g gitbook-cli          
          gitbook install
          npm install -g gitbook-summary
      - name: generate _book folder
        run: |
          book sm
          ln -s -f SUMMARY.md README.md
          gitbook pdf
          gitbook epub

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Release PDF Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: book.pdf
          asset_name: book.pdf